# docker image settings, required section
container:
  # Image name to start on worker, required param.
  image: sonm/eth-claymore:latest
  # Env variables that will be passed to container on start.
  env:
    WALLET: <addr>
    # Ethereum mining params
    # POOL: <pool>
    # WORKER: <worker>
    # EMAIL: <email>

    # Pascal mining params.
    # Set address to enable dual mining with PascalCoin
    # PASC_ADDRESS: <addr>
    # PASC_PAYMENTID: 0
