container:
  commit_on_stop: false
  image: sonm/cryptodredge:v0.20.1
  env:
    # Set params for miner (algo, pool, wallet, etc.), for example PARAMS: "-a x16r -o stratum+tcp://us.ravenminer.com:6789 -u RTCuL6Lod8wL9FgcCj7qKDQibiMBXh1a7F -p worker1"
    PARAMS: ""
